<?php

use Eep\Form\CohortForm as CF;

$this->headTitle('Cohortes');
$newForm->prepare();
$queryForm->prepare();
$deleteForm->prepare();
?>
<div id="general-level" class="tab-pane fade in active">
    <div class="col-lg-4">
        <div class="panel panel-green">
            <div class="panel-heading">
                Creación de Cohorte
            </div>
            <div class="panel-body pan">
                <?= $this->form()->openTag($newForm) ?>
                <div class="form-body pal">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label for="inputName" class="control-label">
                                    Fecha de Cohorte
                                    <button type="button" data-container="body" data-toggle="popover" data-placement="top" 
                                            data-content="La fecha de cohorte determina el pensum, nombre y costo de los cursos" 
                                            class="btn-info" data-original-title="" title="">
                                        <i class="fa fa-info"></i>
                                    </button>
                                </label>
                                <div class="input-icon">
                                    <i class="fa fa-calendar"></i>
                                    <?= $this->formElement($newForm->get(CF::COHORT)) ?>
                                    <font color="red"><?= $this->formElementErrors($newForm->get(CF::COHORT)) ?></font>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?= $this->partial('eep/msg', ['msg' => isset($newMsg) ? $newMsg : null]) ?>
                </div>
                <div class="form-actions text-right pal">
                    <?= $this->formElement($newForm->get(CF::TYPE_NEW)) ?>
                </div>
                <?= $this->form()->closeTag($newForm) ?>
            </div>
        </div>
    </div>
    <div class="col-lg-8">
        <div class="panel panel-green">
            <div class="panel-heading">Búsqueda de Cohortes</div>
            <div class="panel-body">
                <div class="row">
                    <?= $this->form()->openTag($queryForm) ?>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <?= $this->formLabel($queryForm->get(CF::START_DATE)) ?>
                            <div class="input-icon">
                                <i class="fa fa-calendar-o"></i>
                                <?= $this->formElement($queryForm->get(CF::START_DATE)) ?>
                                <font color="red"><?= $this->formElementErrors($queryForm->get(CF::START_DATE)) ?></font>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <?= $this->formLabel($queryForm->get(CF::FINISH_DATE)) ?>
                            <div class="input-icon">
                                <i class="fa fa-calendar"></i>
                                <?= $this->formElement($queryForm->get(CF::FINISH_DATE)) ?>
                                <font color="red"><?= $this->formElementErrors($queryForm->get(CF::FINISH_DATE)) ?></font>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <br/>
                        <?= $this->formElement($queryForm->get(CF::TYPE_QUERY)) ?>
                    </div>
                    <?= $this->form()->closeTag($queryForm) ?>
                </div>
                <hr/>
                <?= $this->partial('eep/msg', ['msg' => isset($deleteMsg) ? $deleteMsg : null]) ?>
                <?php
                if (isset($cohorts)):
                    ?>
                    <table class="table table-hover table-striped">
                        <thead>
                            <tr>
                                <th class="text-center">Fecha Cohorte</th>
                                <th class="text-center">Eliminar 
                                    <button type="button" data-container="body" data-toggle="popover" data-placement="top" 
                                            data-content="Para eliminar una cohorte, esta no debe tener estudiantes asignados ni horarios de cursos asociadas." 
                                            class="btn-info" data-original-title="" title="">
                                        <i class="fa fa-info"></i>
                                    </button>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            if (!empty($cohorts)):
                                foreach ($cohorts as $cohort):
                                    echo $this->form()->openTag($deleteForm);
                                    ?>
                                    <tr>
                                        <td  class="text-center" style="vertical-align:middle;"><?= date('d/m/Y', strtotime($cohort['fecha_cohorte'])) ?></td>
                                        <td class="text-center">
                                            <button type="submit" name="<?= CF::DELETE_COHORT ?>" class="btn btn-red" value="<?= $cohort['fecha_cohorte'] ?>">
                                                <i class="fa fa-trash"></i>
                                            </button>
                                        </td>
                                    </tr>
                                    <?php
                                    echo $this->form()->closeTag($deleteForm);
                                endforeach;
                            endif;
                            ?>
                        </tbody>
                    </table>
                    <?php
                endif;
                ?>

            </div>
        </div>
    </div>
</div>