<?php

use Eep\Form\CohortUsersForm as CUF;

$this->headTitle('Estudiantes Cohorte');
$form->prepare();
$role = $this->layout()->role;
?>
<div class="col-md-12">
    <div class="panel panel-<?= ($role->hasAdminRole()) ? 'green' : 'blue' ?>">
        <div class="panel-heading">
            Listado de Estudiantes por Cohorte
        </div>
        <div class="panel-body">
            <?= $this->form()->openTag($form) ?>
            <div class="row">
                <div class="form-body pal">
                    <div class="col-md-2"></div>

                    <div class="form-group">
                        <?= $this->formLabel($form->get(CUF::COHORT)) ?>
                        <div class="col-md-5">
                            <?= $this->formElement($form->get(CUF::COHORT)) ?>
                            <font color = "red"><?= $this->formElementErrors($form->get(CUF::COHORT)) ?></font>
                        </div>
                        <div class="col-md-1 text-center">
                            <?= $this->formElement($form->get(CUF::SUBMIT)) ?>
                        </div>
                    </div>
                </div>
            </div>
            <?= $this->form()->closeTag($form) ?>
            <hr />
            <?php if (!empty($careers)): ?>
                <div class="row">
                    <div class="form-body pal">
                        <?php
                        foreach ($careers as $career => $students):
                            ?>
                            <h3><?= $career ?></h3>
                            <table class="table table-hover table-striped">
                                <thead>
                                    <tr>
                                        <th>CUI/Pasaporte</th>
                                        <th>Reg. Acad.</th>
                                        <th>Nombres</th>
                                        <th>Apellidos</th>
                                        <th>Teléfono</th>
                                        <th>Correo</th>
                                        <th>País</th>
                                        <th>Sexo</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                    foreach ($students as $user):
                                        ?>
                                        <tr>
                                            <td><?= (!empty($user->getCui())) ? $user->getCui() : ($user->getPasaporte() == null ? '' : $user->getPasaporte()) ?></td>
                                            <td><?= (!empty($user->getRegistroAcademico())) ? $user->getRegistroAcademico() : "(pendiente)" ?></td>
                                            <td><?= $user->getNombres() ?></td>
                                            <td><?= $user->getApellidos() ?></td>
                                            <td><?= $user->getTelefono() ?></td>
                                            <td><?= $user->getCorreo() ?></td>
                                            <td><?= $user->getPais() ?></td>
                                            <td> <?php $isMale = ($user->getSexo() == 'H'); ?>
                                                <i class="fa fa-<?= ($isMale) ? "" : "fe" ?>male" style="color:<?= $isMale ? "blue" : "palevioletred" ?>;"></i> 
                                                <?= ($user->getSexo() == 'H') ? "Hombre" : "Mujer" ?>
                                            </td>
                                        </tr>

                                        <?php
                                    endforeach;
                                    ?>
                                </tbody>
                            </table>
                            <?php
                        endforeach;
                        ?>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>