
<?php

use Eep\Controller\GP;
use Eep\Form\PonderBlocksForm as PF;

$this->headTitle('Ponderación de Sección');
?>
<div class="col-lg-12">
    <div class="panel panel-<?= $this->layout()->role->hasAdminRole() ? 'green':'blue' ?>">
        <div class="panel-heading">
            <?php
            if ($timetable != null) {
                echo $timetable->getNombreCurso() . ', sección ' . $timetable->getSeccion() . '. Cohorte ' . ($timetable->getFechaCohorte() == null ? '(CA)' : date('d/m/Y', strtotime($timetable->getFechaCohorte()))) . '. Impartido en ' . GP::MONTHS[$timetable->getMes()] . '/' . $timetable->getAnio();
            } else {
                echo 'Sin horario';
            }
            ?>
        </div>
        <?php
        if ($blocks === null):
            ?>
            <div class="form-body pal">
                <?= $this->partial('eep/msg', ['msg' => $msg ?? null]) ?>
            </div>
            <?php
        else:
            $editable = false;
            foreach ($blocks as $block) {
                if ($block['notas'] == 0) {
                    $editable = true;
                }
            }
            if(count($blocks) == 0){
                $editable = true;
            }
            if ($editable):
                ?>
                <div class="row">
                    <div class="form-body pal">
                        <div class="col-md-8">
                            <div class="form-group">
                                <label class="control-label" for="correo">
                                    Nombre del bloque de ponderación
                                </label>
                                <div class="input-icon">
                                    <i class="fa fa-puzzle-piece"></i>
                                    <input type="text" id="<?= PF::BLOCK_NAME ?>" class="form-control"
                                           placeholder="Ingresa el nombre del trabajo">
                                </div>
                                <font color="red" id="nameError"></font>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label class="control-label" for="correo">
                                    Punteo
                                </label>
                                <div class="input-icon">
                                    <i class="fa fa-star-half-o"></i>
                                    <input type="text" id="<?= PF::BLOCK_VALUE ?>" class="form-control"
                                           placeholder="Ej.: 5.25 (2 decimales max.)">
                                </div>
                                <font color="red" id="valueError"></font>
                            </div>	
                        </div>
                        <div class="col-md-1 text-center">
                            <br>
                            <button type="button" id="add" class="btn btn-green" value="">
                                <i class="fa fa-plus"></i>
                            </button>                            
                        </div>
                    </div>
                </div>
                <form method="post">
                    <?php
                endif;
                ?>
                <input type="hidden" name="<?= PF::TIMETABLE ?>" value="<?= $timetable != null ? $timetable->getCode() : null ?>"
                       <hr/>
                <div class="panel-body pal">
                    <?= $this->partial('eep/msg', ['msg' => $msg ?? null]) ?>
                    <div class="overflow-x" id="tableDiv">
                        <table class="table table-bordered table-condensed">
                            <thead>
                                <tr>
                                    <th class="text-center">Nombre del bloque</th>
                                    <th class="text-center">Valor</th>
                                    <th class="text-center">Acción</th>
                                </tr>
                            </thead>
                            <tbody id="blockRows">
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th class="text-right">TOTAL</th>
                                    <th class="text-center"><b><i id="total"></i> pts.</b></th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
                <?php
                if ($editable):
                    ?>
                    <div class="form-actions text-right pal">
                        <div class="form-group">
                            <button type="submit" id="submit" class="btn btn-primary" disabled="disabled">
                                Guardar cambios
                            </button>
                        </div>
                    </div>
                </form>
                <?php
            endif;
        endif;
        ?>
    </div>
</div>

<script type="text/javascript">
    var blocks = <?= json_encode($blocks) ?>;
    var blockCodeElement = "<?= PF::BLOCK_CODE ?>";
    var blockNameElement = "<?= PF::BLOCK_NAME ?>";
    var blockValueElement = "<?= PF::BLOCK_VALUE ?>";
</script>
<script type="text/javascript" src="<?= $this->basePath('/js/ponderingTable.js') ?>"></script>
