<?php
$this->headTitle('Iniciar Sesión');

use Eep\Form\LoginForm;

$form->prepare();
?>
<div class="col-lg-4"></div>
<div class="col-lg-4">
    <div class="panel panel-blue">
        <div class="panel-heading">
            Inicio de Sesión</div>
        <div class="panel-body pan">
            <!--            <form action="#">-->
            <?= $this->form()->openTag($form) ?>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <div class="input-icon">
                                <i class="fa fa-key"></i>
<!--                                    <input id="inputLastName" type="password" placeholder="Contraseña" class="form-control" />-->
                                <?= $this->formElement($form->get(LoginForm::PASS)) ?>
                                <font color="red"><?= $this->formElementErrors($form->get(LoginForm::PASS)) ?></font>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <?= $this->formElement($form->get('remember_me')) ?>
                            <?= $this->formLabel($form->get('remember_me')) ?>
                            <?= $this->formElement($form->get(LoginForm::REDIRECT)) ?>
                        </div>
                    </div>
                </div>
                <?php echo $this->partial('eep/msg', ['msg' => isset($this->message) ? $this->message : null]); ?>
            </div>
            <div class="form-actions w-100 d-flex justify-content-between align-items-center" style="width: 100%; display: flex; justify-content: space-between; align-items: center; margin-top: 10px;">
                <a href="/recover-password" class="btn btn-link">¿Olvidaste tu contraseña?</a>
                <?= $this->formElement($form->get(LoginForm::SIGN_IN)) ?>
            </div>
            <!--            </form>-->
            <?= $this->form()->closeTag($form) ?>
        </div>
    </div>
</div>