<?php

use Eep\Form\ChangePassForm;

$this->headTitle('Cambio de contraseña');
$form->prepare();
?>
<div class="col-lg-3"></div>
<div class="col-lg-6">
    <div class="panel panel-<?= ($this->layout()->userType == 'admin') ? 'green' : 'blue' ?>">
        <div class="panel-heading">
            Ingreso de contraseña</div>
        <div class="panel-body pan">
            <?= $this->form()->openTag($form) ?> 
            <div class="form-body pal">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <div class="input-icon">
                                <i class="fa fa-unlock-alt"></i>
    <!--                                <input id="inputFirstName" type="password" placeholder="Contraseña anterior" class="form-control" /></div>-->
                                <?= $this->formElement($form->get(ChangePassForm::ACTUAL)) ?>
                                <font color="red"><?= $this->formElementErrors($form->get(ChangePassForm::ACTUAL)) ?> </font>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <div class="input-icon">
                                <i class="fa fa-key"></i>
    <!--                                    <input id="inputFirstName" type="password" placeholder="Nueva Contraseña" class="form-control" /></div>-->
                                <?= $this->formElement($form->get(ChangePassForm::NEW_PASS)) ?>
                                <font color="red"><?= $this->formElementErrors($form->get(ChangePassForm::NEW_PASS)) ?> </font>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <div class="input-icon">
                                <i class="fa fa-key"></i>
    <!--                                    <input id="inputLastName" type="password" placeholder="Repetir Contraseña" class="form-control" /></div>-->
                                <?= $this->formElement($form->get(ChangePassForm::CONFIRM_PASS)) ?>
                                <font color="red"><?= $this->formElementErrors($form->get(ChangePassForm::CONFIRM_PASS)) ?> </font>
                            </div>
                        </div>
                    </div>
                </div>
                <?php if ($this->message != null): ?>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <div class="note note-<?= $this->message->getType() ?>">
                                    <h4 class="box-heading">
                                        <?= $this->message->getTitle(); ?>
                                    </h4>
                                    <p>
                                        <?= $this->message->getMessage(); ?>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
            <div class="form-actions text-right pal">
                <!-- <button type="submit" class="btn btn-primary">Cambiar contraseña</button>-->
                <?= $this->formElement($form->get(ChangePassForm::SIGN_IN)) ?>
            </div>
            <?= $this->form()->closeTag($form) ?>
        </div>
    </div>
</div>