<?php
$this->headTitle('Recuperar Contraseña');

/** @var \Eep\Form\RecoverPasswordForm $form */
/** @var \Eep\ValueObject\Message|null $msg */

$form->prepare();
?>
<div class="col-lg-4"></div>
<div class="col-lg-4">
    <div class="panel panel-blue">
        <div class="panel-heading">
            Recuperar contraseña</div>
        <div class="panel-body pan">
            <?= $this->form()->openTag($form) ?>
            <div class="form-body pal">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <div class="input-icon">
                                <i class="fa fa-envelope"></i>
                                <?= $this->formElement($form->get('email')) ?>
                            </div>
                            <font color="red"><?= $this->formElementErrors($form->get('email')) ?></font>
                        </div>
                    </div>
                </div>
                <?php echo $this->partial('eep/msg', ['msg' => isset($msg) ? $msg : null]); ?>
            </div>
            <div class="form-actions w-100 d-flex justify-content-between align-items-center" style="width: 100%; display: flex; justify-content: space-between; align-items: center; margin-top: 10px;">
                <a href="<?php echo $this->url('auth', ['action' => 'login']); ?>" class="btn btn-link">Volver al login</a>
                <?= $this->formElement($form->get('submit')) ?>
            </div>
            <?= $this->form()->closeTag($form) ?>
        </div>
    </div>
</div>
