<?= $this->doctype() ?>
<html lang="en">
    <head>
        <?= $this->headTitle('Arquitectura')->setSeparator(' - ')->setAutoEscape(false) ?>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!--Loading bootstrap css-->
        <link type="text/css" rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,300,700">
        <link type="text/css" rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oswald:400,700,300">


        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/arquitectura-logo.png'])
                ->appendStylesheet($this->basePath('styles/jquery-ui-1.10.4.custom.min.css'))
                ->appendStylesheet($this->basePath('styles/font-awesome.min.css'))
                ->appendStylesheet($this->basePath('styles/bootstrap.min.css'))
                ->appendStylesheet($this->basePath('styles/animate.css'))
                ->appendStylesheet($this->basePath('styles/all.css'))
                ->appendStylesheet($this->basePath('styles/main.css'))
                ->appendStylesheet($this->basePath('styles/style-responsive.css'))
                ->appendStylesheet($this->basePath('styles/zabuto_calendar.min.css'))
                ->appendStylesheet($this->basePath('styles/pace.css'))
                ->appendStylesheet($this->basePath('styles/jquery.news-ticker.css'))
                ->appendStylesheet($this->basePath('styles/nestable.css'))
        ?>

    </head>
    <body>
        <div>
            <!--BEGIN BACK TO TOP-->
            <a id="totop" href="#"><i class="fa fa-angle-up"></i></a>
            <!--END BACK TO TOP-->
            <!--BEGIN TOPBAR-->
            <div id="header-topbar-option-demo" class="page-header-topbar">
                <nav id="topbar" role="navigation" style="margin-bottom: 0;" data-step="3" class="navbar navbar-default navbar-static-top">
                    <div class="topbar-main">
                        <div class="navbar-header">
                            <button type="button" data-toggle="collapse" data-target=".sidebar-collapse" class="navbar-toggle"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
                            <a id="logo" href="<?= $this->url('home') ?>" class="navbar-brand"><span class="fa fa-rocket"></span><span class="logo-text">Arquitectura</span><span style="display: none" class="logo-text-icon">µ</span></a></div>
                    </div>
                </nav>
            </div>
            <!--END TOPBAR-->
            <!--BEGIN SIDEBAR MENU-->
            <!--BEGIN CONTENT-->
            <div class="page-content">
                <div id="tab-general">
                    <div class="row mbl">
                        <div class="col-lg-12">

                            <div class="col-md-12">
                                <div id="area-chart-spline" style="width: 100%; height: 300px; display: none;">
                                </div>
                            </div>
                            <?= $this->content ?>
                        </div>
                    </div>
                </div>
                <!--END CONTENT-->
                <!--BEGIN FOOTER-->
                <div id="footer">
                    Escuela de Estudios de Postgrado, Facultad de Arquitectura, USAC.
                </div>
                <!--END FOOTER-->
                <!--END PAGE WRAPPER-->
            </div>




            <?php
            echo $this->inlineScript()
                    ->appendFile($this->basePath("script/jquery-1.10.2.min.js"))
                    ->appendFile($this->basePath("script/jquery-migrate-1.2.1.min.js"))
                    ->appendFile($this->basePath("script/jquery-ui.js"))
                    ->appendFile($this->basePath("script/bootstrap.min.js"))
                    ->appendFile($this->basePath("script/bootstrap-hover-dropdown.js"))
                    ->appendFile($this->basePath("script/html5shiv.js"))
                    ->appendFile($this->basePath("script/respond.min.js"))
                    ->appendFile($this->basePath("script/jquery.metisMenu.js"))
                    ->appendFile($this->basePath("script/jquery.slimscroll.js"))
                    ->appendFile($this->basePath("script/jquery.cookie.js"))
                    ->appendFile($this->basePath("script/icheck.min.js"))
                    ->appendFile($this->basePath("script/custom.min.js"))
                    ->appendFile($this->basePath("script/jquery.news-ticker.js"))
                    ->appendFile($this->basePath("script/jquery.menu.js"))
                    ->appendFile($this->basePath("script/pace.min.js"))
                    ->appendFile($this->basePath("script/holder.js"))
                    ->appendFile($this->basePath("script/responsive-tabs.js"))
                    ->appendFile($this->basePath("script/jquery.flot.js"))
                    ->appendFile($this->basePath("script/jquery.flot.categories.js"))
                    ->appendFile($this->basePath("script/jquery.flot.pie.js"))
                    ->appendFile($this->basePath("script/jquery.flot.tooltip.js"))
                    ->appendFile($this->basePath("script/jquery.flot.resize.js"))
                    ->appendFile($this->basePath("script/jquery.flot.fillbetween.js"))
                    ->appendFile($this->basePath("script/jquery.flot.stack.js"))
                    ->appendFile($this->basePath("script/jquery.flot.spline.js"))
                    ->appendFile($this->basePath("script/zabuto_calendar.min.js"))
                    ->appendFile($this->basePath("script/index.js"))
                    ->appendFile($this->basePath("script/highcharts.js"))
                    ->appendFile($this->basePath("script/data.js"))
                    ->appendFile($this->basePath("script/drilldown.js"))
                    ->appendFile($this->basePath("script/exporting.js"))
                    ->appendFile($this->basePath("script/highcharts-more.js"))
                    ->appendFile($this->basePath("script/charts-highchart-pie.js"))
                    ->appendFile($this->basePath("script/charts-highchart-more.js"))

//                ->appendFile($this->basePath("script/animation.js"))
//                ->appendFile($this->basePath("script/charts-chartjs.js"))
//                ->appendFile($this->basePath("script/charts-flotchart.js"))
//                ->appendFile($this->basePath("script/charts-highchart-area.js"))
//                ->appendFile($this->basePath("script/charts-highchart-column-bar.js"))
//                ->appendFile($this->basePath("script/charts-highchart-combinations.js"))
//                ->appendFile($this->basePath("script/charts-highchart-dynamic.js"))
//                ->appendFile($this->basePath("script/charts-highchart-line.js"))
//                ->appendFile($this->basePath("script/charts-highchart-scatter-bubble.js"))
//                ->appendFile($this->basePath("script/funnel.js"))
//                ->appendFile($this->basePath("script/highchart.js"))
//                ->appendFile($this->basePath("script/jplist.js"))
//                ->appendFile($this->basePath("script/jplist.min.js"))
//                ->appendFile($this->basePath("script/modernizr.min.js"))
                    ->appendFile($this->basePath("script/main.js"))
                    ->appendFile($this->basePath("script/jquery.nestable.js"))
                    ->appendFile($this->basePath("script/ui-nestable-list.js"))
            ?>

    </body>
</html>
