<!DOCTYPE html>
<html lang="en">
    <head>
        <?= $this->headTitle('Arquitectura')->setSeparator(' - ')->setAutoEscape(false) ?>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!--Loading bootstrap css-->
        <link type="text/css" rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,300,700">
        <link type="text/css" rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oswald:400,700,300">


        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/arquitectura-logo.png'])
                ->appendStylesheet($this->basePath('styles/jquery-ui-1.10.4.custom.min.css'))
                ->appendStylesheet($this->basePath('styles/font-awesome.min.css'))
                ->appendStylesheet($this->basePath('styles/bootstrap.min.css'))
                ->appendStylesheet($this->basePath('styles/animate.css'))
                ->appendStylesheet($this->basePath('styles/all.css'))
                ->appendStylesheet($this->basePath('styles/main.css'))
                ->appendStylesheet($this->basePath('styles/style-responsive.css'))
                ->appendStylesheet($this->basePath('styles/zabuto_calendar.min.css'))
                ->appendStylesheet($this->basePath('styles/pace.css'))
                ->appendStylesheet($this->basePath('styles/jquery.news-ticker.css'))
                ->appendStylesheet($this->basePath('styles/nestable.css'))
        ?>
        <style type="text/css">
            .overflow-x {
                overflow-x:auto;
            }
        </style>
    </head>
    <body>
        <?php
        echo $this->inlineScript()
                ->appendFile($this->basePath("script/jquery-1.10.2.min.js"))
//                ->appendFile($this->basePath("script/jquery-1.10.1.min.js"))
//                ->appendFile($this->basePath("script/jquery-3.3.1.min.js"))
                ->appendFile($this->basePath("script/jquery-migrate-1.2.1.min.js"))
                ->appendFile($this->basePath("script/jquery-ui.js"))
                ->appendFile($this->basePath("script/bootstrap.min.js"))
                ->appendFile($this->basePath("script/bootstrap-hover-dropdown.js"))
                ->appendFile($this->basePath("script/html5shiv.js"))
                ->appendFile($this->basePath("script/respond.min.js"))
                ->appendFile($this->basePath("script/jquery.metisMenu.js"))
                ->appendFile($this->basePath("script/jquery.slimscroll.js"))
                ->appendFile($this->basePath("script/jquery.cookie.js"))
                ->appendFile($this->basePath("script/icheck.min.js"))
                ->appendFile($this->basePath("script/custom.min.js"))
                ->appendFile($this->basePath("script/jquery.news-ticker.js"))
                ->appendFile($this->basePath("script/jquery.menu.js"))
                ->appendFile($this->basePath("script/pace.min.js"))
                ->appendFile($this->basePath("script/holder.js"))
                ->appendFile($this->basePath("script/responsive-tabs.js"))
                ->appendFile($this->basePath("script/jquery.flot.js"))
                ->appendFile($this->basePath("script/jquery.flot.categories.js"))
                ->appendFile($this->basePath("script/jquery.flot.pie.js"))
                ->appendFile($this->basePath("script/jquery.flot.tooltip.js"))
                ->appendFile($this->basePath("script/jquery.flot.resize.js"))
                ->appendFile($this->basePath("script/jquery.flot.fillbetween.js"))
                ->appendFile($this->basePath("script/jquery.flot.stack.js"))
                ->appendFile($this->basePath("script/jquery.flot.spline.js"))
                ->appendFile($this->basePath("script/zabuto_calendar.min.js"))
                ->appendFile($this->basePath("script/index.js"))
//                ->appendFile($this->basePath("script/highcharts.js"))
//                ->appendFile($this->basePath("script/data.js"))
//                ->appendFile($this->basePath("script/drilldown.js"))
//                ->appendFile($this->basePath("script/exporting.js"))
//                ->appendFile($this->basePath("script/highcharts-more.js"))
//                ->appendFile($this->basePath("script/charts-highchart-pie.js"))
//                ->appendFile($this->basePath("script/charts-highchart-more.js"))
//                
//                ->appendFile($this->basePath("script/animation.js"))
//                ->appendFile($this->basePath("script/charts-chartjs.js"))
//                ->appendFile($this->basePath("script/charts-flotchart.js"))
//                ->appendFile($this->basePath("script/charts-highchart-area.js"))
//                ->appendFile($this->basePath("script/charts-highchart-column-bar.js"))
//                ->appendFile($this->basePath("script/charts-highchart-combinations.js"))
//                ->appendFile($this->basePath("script/charts-highchart-dynamic.js"))
//                ->appendFile($this->basePath("script/charts-highchart-line.js"))
//                ->appendFile($this->basePath("script/charts-highchart-scatter-bubble.js"))
//                ->appendFile($this->basePath("script/funnel.js"))
//                ->appendFile($this->basePath("script/highchart.js"))
//                ->appendFile($this->basePath("script/jplist.js"))
//                ->appendFile($this->basePath("script/jplist.min.js"))
//                ->appendFile($this->basePath("script/modernizr.min.js"))
                ->appendFile($this->basePath("script/main.js"))
        ?>
        <div>
            <!--BEGIN BACK TO TOP-->
            <a id="totop" href="#"><i class="fa fa-angle-up"></i></a>
            <!--END BACK TO TOP-->
            <!--BEGIN TOPBAR-->
            <div id="header-topbar-option-demo" class="page-header-topbar">
                <nav id="topbar" role="navigation" style="margin-bottom: 0;position: fixed;top: 0;width: 100%;z-index: 5;" data-step="3" class="navbar navbar-default navbar-static-top">
                    <div class="topbar-main"><a id="menu-toggle" href="#" class="hidden-xs"><i class="fa fa-bars"></i></a>
                        <div class="navbar-header">
                            <button type="button" data-toggle="collapse" data-target=".sidebar-collapse" class="navbar-toggle"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
                            <a id="logo" href="<?= $this->url('user') ?>" class="navbar-brand"><span class="fa fa-rocket"></span><span class="logo-text">Arquitectura</span><span style="display: none" class="logo-text-icon">µ</span></a></div>
                        <ul class="nav navbar navbar-top-links navbar-right mbn">
                            <li class="dropdown topbar-user"><a data-hover="dropdown" href="#" class="dropdown-toggle">&nbsp;<span class="hidden-xs">Usuario</span>&nbsp;<span class="caret"></span></a>
                                <ul class="dropdown-menu dropdown-user pull-right">
                                    <li><a href="<?= $this->url('user', ['action' => 'profile']) ?>"><i class="fa fa-user"></i>Mi perfil</a></li>
                                    <li><a href="<?= $this->url('user', ['action' => 'changePassword']) ?>"><i class="fa fa-unlock-alt"></i>Cambiar Contraseña</a></li>
                                    <li><a href="<?= $this->url('auth', ['action' => 'logout']) ?>"><i class="fa fa-key"></i>Cerrar sesión</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
            <!--END TOPBAR-->   
            <div id="wrapper" class="toggled">
                <!--BEGIN SIDEBAR MENU-->
                <nav id="sidebar" role="navigation" data-step="2" data-intro="Template has &lt;b&gt;many navigation styles&lt;/b&gt;"
                     data-position="right" class="navbar-default navbar-static-side" style="z-index: 1;padding-top: 50px;">
                    <div class="sidebar-collapse menu-scroll">
                        <ul id="side-menu" class="nav">

                            <div class="clearfix"></div>

                            <?php
                            if (isset($this->menus) && !empty($this->menus)):
                                foreach ($this->menus as $menu):
                                    ?>
                                    <li 
                                    <?php
                                    if ($menu->isActive()):
                                        $menuTitle = $menu->getName();
                                        echo 'class="active"';
                                    endif;
                                    ?> 
                                        >
                                        <a href="<?= $this->url($menu->getSection(), ['action' => $menu->getAction()]) ?>">
                                            <i class="fa <?php echo $menu->getIcon(); ?>">

                                            </i>
                                            <span class="menu-title"><?php echo $menu->getName(); ?> </span>
                                        </a>
                                    </li>
                                    <?php
                                endforeach;
                            else:
                                ?>
                                <li class="active">
                                    <a href="">
                                        <i class="fa fa-edit fa-fw">
                                            <div class="icon-bg bg-violet"></div>
                                        </i>
                                        <span class="menu-title">Ninguna sección encontrada</span>
                                    </a>
                                </li>
                            <?php
                            endif;
                            ?>


                        </ul>
                    </div>
                </nav>


                <div id="page-wrapper" style="padding-top: 50px;">
                    <!--BEGIN TITLE & BREADCRUMB PAGE-->
                    <div id="title-breadcrumb-option-demo" class="page-title-breadcrumb" style="padding-top: 60px;">
                        <div class="page-header pull-left <?= (!empty($role) && $role->hasRole() && ($role->hasAdminRole()) || $role->hasUdicaRole()) ? 'admin' : 'student' ?>">
                            <div class="page-title">
                                <?= $menuTitle ?? '' ?>
                            </div>                            
                        </div>
                        <div class="clearfix">
                        </div>
                    </div>
                    <!--END TITLE & BREADCRUMB PAGE-->
                    <!--BEGIN CONTENT-->
                    <div class="page-content">
                        <div id="tab-general">
                            <div class="row mbl">
                                <div class="col-lg-12">

                                    <div class="col-md-12">
                                        <div id="area-chart-spline" style="width: 100%; height: 300px; display: none;">
                                        </div>
                                    </div>

                                </div>

                                <?= $this->content ?>
                            </div>
                        </div>
                    </div>
                    <!--END CONTENT-->
                    <!--BEGIN FOOTER-->
                    <div id="footer">
                        <div class="copyright">
                            Escuela de Estudios de Postgrados, Facultad de Arquitectura</div>
                    </div>
                    <!--END FOOTER-->
                </div>
                <!--END PAGE WRAPPER-->
            </div>
        </div>

        <?php
        echo ""//$this->inlineScript()
//                ->appendFile($this->basePath("script/jquery.nestable.js"))
//                ->appendFile($this->basePath("script/ui-nestable-list.js"))
        ?>

    </body>
</html>