
<?php
$this->headTitle('Horario de Cursos');
$role = $this->layout()->role;
?>
<div class="col-lg-12">
    <div class="panel panel-<?= (empty($role) ? 'blue' : ($role->hasAdminRole() ? 'green' : 'blue')) ?>">
        <div class="panel-heading">Horarios de Cursos Activos</div>
        <div class="panel-body">
            <?= $this->partial('eep/msg', ['msg' => $msg ?? null]) ?>
            <?php
            if (isset($careers)):
                foreach ($careers as $careerName => $timetables):
                    ?>
                    <h3><?= $careerName ?></h3>
                    <div class="overflow-x">
                        <table class="table table-hover table-striped">
                            <thead>
                                <tr>
                                    <?= $role->hasAdminRole() && (current($timetables)->getCodPensum() != Eep\Entity\Order::CURSO_ACTUALIZACION) ? '<th>Cohorte</th>' : '' ?>
                                    <th>Cód.</th>
                                    <th>Curso</th>
                                    <th>Sec.</th>
                                    <th>F. Inicio</th>
                                    <th>F. Fin</th>
                                    <th>Hr. Inicio</th>
                                    <th>Hr. Fin</th>
                                    <th>Lugar</th>
                                    <th>Días</th>
                                    <th>Catedrático</th>
                                    <th>Lab.</th>
                                </tr>
                            </thead>

                            <tbody>

                                <?php
                                foreach ($timetables as $timetable):
                                    ?>
                                    <tr>
                                        <?php
                                        if ($role->hasAdminRole() && ($timetable->getCodPensum() != Eep\Entity\Order::CURSO_ACTUALIZACION)):
                                            $cohort = $timetable->getFechaCohorte();
                                            ?>
                                            <td><?= empty($cohort) ? '' : date('d/m/Y', strtotime($cohort)) ?></td>
                                            <?php
                                        endif;
                                        ?>
                                        <td><?= $timetable->getCodCurso() ?></td>
                                        <td><?= $timetable->getAliasCurso() ?></td>
                                        <td><?= $timetable->getSeccion() ?></td>
                                        <td><?= date('d/m/Y', strtotime($timetable->getFechaInicio())) ?></td>
                                        <td><?= date('d/m/Y', strtotime($timetable->getFechaFin())) ?></td>
                                        <td><?= date('H:i', strtotime($timetable->getHoraInicio())) ?></td>
                                        <td><?= date('H:i', strtotime($timetable->getHoraFin())) ?></td>
                                        <td><?= $timetable->getUbicacion() ?></td>
                                        <td>
                                            <span style="float:left;" class="label label-sm label-<?= $timetable->getLunes() ? 'success' : 'default' ?>">L</span>
                                            <span style="float:left;" class="label label-sm label-<?= $timetable->getMartes() ? 'success' : 'default' ?>">M</span>
                                            <span style="float:left;" class="label label-sm label-<?= $timetable->getMiercoles() ? 'success' : 'default' ?>">X</span>
                                            <span style="float:left;" class="label label-sm label-<?= $timetable->getJueves() ? 'success' : 'default' ?>">J</span>
                                            <span style="float:left;" class="label label-sm label-<?= $timetable->getViernes() ? 'success' : 'default' ?>">V</span>
                                            <span style="float:left;" class="label label-sm label-<?= $timetable->getSabado() ? 'success' : 'default' ?>">S</span>
                                            <span style="float:left;" class="label label-sm label-<?= $timetable->getDomingo() ? 'success' : 'default' ?>">D</span>
                                        </td>
                                        <td><?= $timetable->getCatedratico() ?></td>
                                        <td>
                                            <font color ="<?= $timetable->getLaboratorio() == true ? 'green' : 'red' ?>">
                                            <i class="fa fa-<?= $timetable->getLaboratorio() == true ? 'check' : 'close' ?>"></i>
                                            </font>
                                        </td>
                                    </tr>
                                    <?php
                                endforeach;
                                ?>
                            </tbody>
                        </table>
                    </div>
                    <?php
                endforeach;
            endif;
            ?>
        </div>
    </div>
</div>
