<?php

//CONSTANTS
use Eep\Entity\Role;
use Eep\ValueObject\View;

return [//ICON, MENU text
    View::PROFILE => [
        'controller' => 'user',
        'action' => 'profile',
        'icon' => 'fa-user',
        'text' => 'Mi perfil',
        'roles' => [Role::AUTH]],
    View::COHORTS => [
        'controller' => 'cohort',
        'action' => 'cohorts',
        'icon' => 'fa-clone',
        'text' => 'Cohortes',
        'roles' => [Role::DIRECTOR]],
    View::COHORT_STUDENTS => [
        'controller' => 'cohort',
        'action' => 'cohortStudents',
        'icon' => 'fa-group',
        'text' => 'Estudiantes por Cohorte',
        'roles' => [Role::DIRECTOR, Role::TESORERO, Role::ASISTENTE, Role::UDICA_JEFE, Role::UDICA_OPERADOR]],
    View::STUDENT_SEARCH => [
        'controller' => 'user',
        'action' => 'studentSearch',
        'icon' => 'fa-search',
        'text' => 'Búsqueda de usuarios',
        'roles' => [Role::DIRECTOR, Role::TESORERO, Role::ASISTENTE, Role::UDICA_JEFE, Role::UDICA_OPERADOR]],
    View::UPG_COURSES => [
        'controller' => 'upgCourse',
        'action' => 'view',
        'icon' => 'fa-refresh',
        'text' => 'Cursos de Actualización',
        'roles' => [Role::DIRECTOR, Role::UDICA_JEFE]],
    View::CANDIDATES => [
        'controller' => 'user',
        'action' => 'candidates',
        'icon' => 'fa-user-plus',
        'text' => 'Ingreso de Aspirantes',
        'roles' => [Role::ASISTENTE, Role::DIRECTOR]],
    View::SCHEDULING => [
        'controller' => 'timetable',
        'action' => 'categorize',
        'icon' => 'fa-calendar-plus-o',
        'text' => 'Calendarización',
        'roles' => [Role::DIRECTOR, Role::ASISTENTE]],
    View::AVAILABLE_COURSES => [
        'controller' => 'timetable',
        'action' => 'availableCourses',
        'icon' => 'fa-th-list',
        'text' => 'Horario de Cursos',
        'roles' => [Role::AUTH]],
    View::INSCRIPTION => [
        'controller' => 'inscription',
        'action' => 'view',
        'icon' => 'fa-edit',
        'text' => 'Inscripción Primer Año',
        'roles' => [Role::ESTUDIANTE]],
    View::ASSIGNMENT => [
        'controller' => 'assignment',
        'action' => 'assignment',
        'icon' => 'fa-sign-in',
        'text' => 'Asignación de Cursos',
        'roles' => [Role::ESTUDIANTE]],
    View::ADMIN_ASSIGNMENT => [
        'controller' => 'assignment',
        'action' => 'assignmentType',
        'icon' => 'fa-sign-out',
        'text' => 'Asignación Administrativa',
        'roles' => [Role::DIRECTOR, Role::ASISTENTE]],
    View::ORDER_LISTING => [
        'controller' => 'treasury',
        'action' => 'orderListing',
        'icon' => 'fa-sticky-note',
        'text' => 'Órdenes de Pago',
        'roles' => [Role::DIRECTOR, Role::TESORERO, Role::ESTUDIANTE, Role::UDICA_JEFE, Role::ASISTENTE]],
    View::ASSIGNED_COURSES => [
        'controller' => 'assignment',
        'action' => 'assignedCourses',
        'icon' => 'fa-tasks',
        'text' => 'Cursos Asignados',
        'roles' => [Role::DIRECTOR, Role::ASISTENTE, Role::UDICA_JEFE, Role::UDICA_OPERADOR, Role::ESTUDIANTE, Role::TESORERO]],
    View::OFFICIAL_COURSES => [
        'controller' => 'user',
        'action' => 'officialCourses',
        'icon' => 'fa-book',
        'text' => 'Cursos Oficializados',
        'roles' => [Role::DIRECTOR, Role::ASISTENTE, Role::UDICA_JEFE, Role::UDICA_OPERADOR, Role::UDICA_PROGRAMADOR, Role::ESTUDIANTE, Role::TESORERO]],
    View::TAUGHT_TIMETABLES => [
        'controller' => 'timetable',
        'action' => 'taught',
        'icon' => 'fa-tasks',
        'text' => 'Cursos Impartidos',
        'roles' => [Role::DIRECTOR, Role::ASISTENTE, Role::CATEDRATICO, Role::COORDINADOR, Role::TESORERO]],
    View::ROLE_ADMIN => [
        'controller' => 'auth',
        'action' => 'roles',
        'icon' => 'fa-street-view',
        'text' => 'Asignación de roles',
        'roles' => [Role::UDICA_JEFE]],
    View::GRAL_REPORT => [
        'controller' => 'treasury',
        'action' => 'gralReport',
        'icon' => 'fa-line-chart',
        'text' => 'Reporte General',
        'roles' => [Role::TESORERO, Role::DIRECTOR, Role::UDICA_JEFE, Role::ASISTENTE]],
    View::PROGRAMMER_OPTIONS => [
        'controller' => 'etl',
        'action' => 'index',
        'icon' => 'fa-laptop',
        'text' => 'Carga de Datos',
        'roles' => [Role::PROGRAMADOR]],
    View::UDICA_PROGRAMMER => [
        'controller' => 'timetable',
        'action' => 'seasonView',
        'icon' => 'fa-calendar-plus-o',
        'text' => 'Temporadas',
        'roles' => [Role::UDICA_PROGRAMADOR]],
    View::OFFICIAL_TIMETABLES => [
        'controller' => 'official',
        'action' => 'timetables',
        'icon' => 'fa-legal',
        'text' => 'Oficialización Regular',
        'roles' => [Role::UDICA_OPERADOR, Role::UDICA_JEFE, Role::UDICA_PROGRAMADOR, Role::DIRECTOR, Role::ASISTENTE]],
    View::MANUAL_OFFICIALIZATION => [
        'controller' => 'official',
        'action' => 'manualEntry',
        'icon' => 'fa-edit',
        'text' => 'Oficialización Manual',
        'roles' => [Role::UDICA_OPERADOR]],
//    View::ORDERS_UPDATE => [
//        'controller' => 'treasury',
//        'action' => 'orderUpdate',
//        'icon' => 'fa-retweet',
//        'text' => 'Actualización de Órdenes',
//        'roles' => [Role::TESORERO]],
    View::LOG_VIEW => [
        'controller' => 'user',
        'action' => 'logView',
        'icon' => 'fa-history',
        'text' => 'Bitácora',
        'roles' => [Role::DIRECTOR, Role::ASISTENTE, Role::TESORERO, Role::UDICA_JEFE]],
    View::FORMULARIO_ADMISION => [
        'controller' => 'formulario-admision',
        'action' => 'index',
        'icon' => 'fa-file-text-o',
        'text' => 'Formulario de Admisión',
        'roles' => [Role::DIRECTOR, Role::ASISTENTE]
    ],
];
